spring:
  data:
    mongodb:
 #     authentication-database:
    # username: ${MONGO_USER}
    # password: ${MONGO_PASSWORD}
     database: CategoryServiceDB
     port: 27018
     host: localhost
  application:
    name: category-service
server:
  port: 8083
