spring:
  data:
    mongodb:
   #   username: ${MONGO_USERNAME}
    #  password: ${MONGO_PASSWORD}
      database: NoteServiceDB
      port: 27018
      host: localhost
  application:
    name: note-service
server:
  port: 8082
